name: Joke Updater

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00
  workflow_dispatch:   # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y jq

      - uses: actions/checkout@v2

      - name: Fetch joke
        id: fetch_joke
        run: |
          JOKE=$(curl -s https://v2.jokeapi.dev/joke/Programming | jq -r '.setup, .delivery | join(" - ")')
          echo "::set-output name=joke::$JOKE"
      
      - name: Update README
        run: |
          JOKE="${{ steps.fetch_joke.outputs.joke }}"
          sed -i "/<!--joke-start-->/,/<!--joke-end-->/c\<!--joke-start-->\n$JOKE\n<!--joke-end-->" README.md

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated Joke"
          git push
