name: Joke Updater

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y jq curl perl

      - uses: actions/checkout@v2

      - name: Fetch joke
        id: fetch_joke
        run: |
          set -e
          set -o pipefail
          JOKE_RESPONSE=$(curl -s https://v2.jokeapi.dev/joke/Programming)
          JOKE_TYPE=$(jq -r '.type' <<< "$JOKE_RESPONSE")
          if [ "$JOKE_TYPE" == "single" ]
          then
              JOKE=$(jq -r '.joke' <<< "$JOKE_RESPONSE" | sed 's/\r//g; s/\n/ /g')
          else
              SETUP=$(jq -r '.setup' <<< "$JOKE_RESPONSE" | sed 's/\r//g; s/\n/ /g')
              DELIVERY=$(jq -r '.delivery' <<< "$JOKE_RESPONSE" | sed 's/\r//g; s/\n/ /g')
              JOKE="$SETUP - $DELIVERY"
          fi
          JOKE=$(echo -n "$JOKE" | xargs -0)
          echo "JOKE=$JOKE" >> $GITHUB_ENV
        shell: bash

      - name: Update README
        run: |
          export JOKE="${{ env.JOKE }}"
          perl -i -p0e 's|<!--joke-start-->.*?<!--joke-end-->|<!--joke-start-->\n$ENV{JOKE}\n<!--joke-end-->|s' README.md
        shell: bash

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated Joke"
          git checkout -b tmp
          git fetch origin main
          git checkout main
          git merge tmp --no-edit
          git push
        shell: bash
