name: Joke Updater

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y jq curl python3

      - uses: actions/checkout@v2

      - name: Fetch joke
        id: fetch_joke
        run: |
          set -e
          set -o pipefail
          JOKE_RESPONSE=$(curl -s https://v2.jokeapi.dev/joke/Programming)
          JOKE_TYPE=$(jq -r '.type' <<< "$JOKE_RESPONSE")
          if [ "$JOKE_TYPE" == "single" ]
          then
              JOKE=$(jq -r '.joke' <<< "$JOKE_RESPONSE")
          else
              SETUP=$(jq -r '.setup' <<< "$JOKE_RESPONSE")
              DELIVERY=$(jq -r '.delivery' <<< "$JOKE_RESPONSE")
              JOKE="$SETUP - $DELIVERY"
          fi
          echo "JOKE=$JOKE" >> $GITHUB_ENV
        shell: bash

      - name: Update README
        run: |
          JOKE="${{ env.JOKE }}"
          python3 -c '
import re

with open("README.md", "r") as file:
  content = file.read()

content = re.sub(r"<!--joke-start-->.*<!--joke-end-->", "<!--joke-start-->\n" + "\"" + JOKE + "\"\n" + "<!--joke-end-->", content, flags=re.DOTALL)

with open("README.md", "w") as file:
  file.write(content)
'
        shell: bash

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated Joke"
          git checkout -b tmp
          git fetch origin main
          git checkout main
          git merge tmp --no-edit
          git push
        shell: bash
